dist: xenial
language: minimal
install: 
  - sudo apt update
  - sudo apt install -y gnutls-bin
script: make web
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: web
  target_branch: gh-pages
  keep_history: false
  verbose: false
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  on:
    branch: master
