dist: bionic    # Ubuntu 18.04 LTS
language: ruby
gemfile: web/Gemfile

before_install: 
  - sudo apt update
  - sudo apt install -y gnutls-bin
  - git clone https://github.com/MestreLion/git-tools # Distro version is currently broken

script: 
  - ./git-tools/git-restore-mtime
  - make check

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

# cache: bundler # caching bundler gem packages will speed up build

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: web
  target_branch: gh-pages
  keep_history: false
  verbose: false
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  on:
    branch: master
